### ISSUE TITLE
Add an 64bits mupdf.dll to the releases

### ISSUE THREAD

**Issue by Sicos1977** [wmjordan/mupdf#7]
Hi,

Can you please add an extra dll to the releases that is also compiled for 64 bits systems?
I tried to compile the project myself but run in all kind of errors.

![image](https://user-images.githubusercontent.com/6692947/67546687-3e117100-f6fd-11e9-93b7-e0baf2c09810.png)

**Comment by wmjordan** [comment]
Don't download the source code, CLONE it. Otherwise you will have trouble with the third-party stuff.

This is the 64bit one. Pls give it a try.
[MuPDFLib.zip](https://github.com/wmjordan/mupdf/files/3770663/MuPDFLib.zip)

**Comment by Sicos1977** [comment]
I did clone it but then all thirdparty stuff is missing. I solved that by cloning the artifex mupdf repository and get it from there.... but then I still get build errors.

**Comment by Sicos1977** [comment]
I found a bug in you MuPdfSharp app, when I set this line to Gray then the programm crashes with an exception

`c# pix = NativeMethods.NewPixmap (context, NativeMethods.FindDeviceColorSpace (context, ColorSpace.Gray), width, height, IntPtr.Zero, 0);`

![image](https://user-images.githubusercontent.com/6692947/67555587-df0a2700-f711-11e9-98e0-3a3e571c0a32.png)

**Comment by wmjordan** [comment]
The third-party stuff in artifex/mupdf might be a little different from this fork.
You may need to redo your clone. Don't forget to clone the submodules recursively.

**Comment by wmjordan** [comment]
> I found a bug in you MuPdfSharp app, when I set this line to Gray then the programm crashes with an exception

It is not a bug. If you use the gray scale color space, each pixel takes only a single byte, whereas a pixel takes three bytes in the RGB color space.

So, you must change the read-write process to accommodate the differences.
The `RtlMoveMemory` will no longer be applicable since the source is a 8-bit gray scale but the target is `Format24bppRgb` (a 24-bit RGB scale). So to the offset adjustment after the line by line copy.

You may have to define `UNSAFE` in your project to turn on the part of unsafe code and begin with there, if you are rendering to the gray scale.

**Comment by Sicos1977** [comment]
This is also not correct.

pix = NativeMethods.NewPixmap (context, NativeMethods.FindDeviceColorSpace (context, ColorSpace.Rgb), width, height, IntPtr.Zero, 0);

You need to use Bgr otherwise colors get inverted

**Comment by Sicos1977** [comment]
Is it also possible to in some way set the resolution for the page you get from muPDF? My PDF has pages that are 600 dpi but when I get them from mupdf they are converted to 200 dpi

**Comment by wmjordan** [comment]
> You need to use Bgr otherwise colors get inverted

😰 Have you ever run my demo without any modification? Isn't it giving correct result to you?

**Comment by wmjordan** [comment]
> Is it also possible to in some way set the resolution for the page you get from muPDF?

You need to render the image to a higher dimension, i.e. much larger height and width values.

**Comment by Sicos1977** [comment]
Do you have an example about how to get the page in a much higher resolution?

I already tried matrix.ScaleTo(width * 10, height * 10); but that does do nothing.

**Comment by Sicos1977** [comment]
Okey I seemed to have figured out how to do the scaling.

            var width = (int) (pageBound.Right - pageBound.Left) * 5;
            var height = (int) (pageBound.Bottom - pageBound.Top) * 5;
            Width = width;
            Height = height;

			matrix.A = matrix.D = 5;
