### ISSUE TITLE
doc.loadImage(ref) - not working

### ISSUE THREAD

**Issue by ManoLazar** [wmjordan/mupdf#8]
I tried some examples with:

mutool.exe run imgs.js

ref = doc.newIndirect(i, 0);
...
	 var obj = doc.loadImage(ref);
throws exception :
warning: invalid indirect reference (0 0 R)

**Comment by wmjordan** [comment]
You've have to use the bug report channel provided by the official mupdf. I am sorry that I could not help you here since I am not supposed to maintain the source code.
